name: zerollama_v0.5
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - anaconda
  - pytorch-cuda=12.1
  - pytorch==2.3.0
  - pip
  - pip:
      - torchvision
      - huggingface_hub
      - transformers==v4.42.4
      - accelerate
      - optimum
      - auto-gptq==0.7.1
      - autoawq==0.2.5
      - prettytable==3.10.0
      - modelscope==1.13.3
      - easydict==1.13
      - uvicorn==0.29.0
      - fastapi==0.110.2
      - pydantic==2.7.1
      - shortuuid==1.0.13
      - FlagEmbedding==1.2.9
      - gevent==24.2.1
      - bitsandbytes==0.43.1