name: zerollama_v0.2
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - anaconda
  - pytorch-cuda=12.1
  - pytorch
  - pip
  - pip:
      - transformers==4.38.2
      - accelerate==0.29.2
      - optimum==1.18.1
      - auto-gptq==0.7.1
      - autoawq==0.2.4
      - prettytable==3.10.0
      - modelscope==1.13.3
      - easydict==1.13
      - uvicorn==0.29.0
      - fastapi==0.110.2
      - pydantic==2.7.1